# Generated by Django 6.0.3 on 2026-05-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_entity_type_entity_idx_entity_code_and_more'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='import_type',
            field=models.CharField(choices=[('presupuesto', 'Presupuesto'), ('indicadores', 'Indicadores'), ('registros', 'Registros de indicadores')], default='indicadores', max_length=20),
        ),
        migrations.AddField(
            model_name='importjob',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='catalog.entity'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='catalog.period'),
        ),
    ]
