# Generated by Django 6.0.3 on 2026-03-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_consolidated', models.BooleanField(default=False, help_text='Indica si esta entidad es la agregada/consolidada del municipio')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('mensual', 'Mensual'), ('acumulado', 'Acumulado'), ('anual', 'Anual')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'periodo',
                'verbose_name_plural': 'periodos',
                'indexes': [models.Index(fields=['year', 'month'], name='idx_period_year_month')],
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'period_type'), name='unique_period')],
            },
        ),
    ]
