# Generated by Django 6.0.3 on 2026-04-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('consolidado', 'Consolidado'), ('empresa', 'Empresa'), ('mipyme', 'Mipyme'), ('unidad_presupuestada', 'Unidad presupuestada')], default='empresa', max_length=40),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['code'], name='idx_entity_code'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name'], name='idx_entity_name'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['type'], name='idx_entity_type'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_consolidated'], name='idx_entity_consolidated'),
        ),
    ]
