# Generated by Django 6.0.3 on 2026-03-27 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_calculations', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='catalog.period')),
            ],
            options={
                'verbose_name': 'calculo',
                'verbose_name_plural': 'calculos',
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculations.calculation')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='catalog.entity')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='indicators.indicator')),
            ],
            options={
                'verbose_name': 'resultado de calculo',
                'verbose_name_plural': 'resultados de calculo',
                'constraints': [models.UniqueConstraint(fields=('calculation', 'entity', 'indicator', 'variable_name'), name='unique_calculation_result')],
            },
        ),
    ]
