# Generated by Django 6.0.3 on 2026-04-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('closed', 'Cerrado')], default='draft', max_length=20),
        ),
    ]
