# Generated by Django 6.0.3 on 2026-03-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('fundamental', 'Fundamental'), ('limite', 'Limite'), ('otro', 'Otro')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'grupo de indicador',
                'verbose_name_plural': 'grupos de indicadores',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(help_text='Codigo unico del indicador', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('MP', 'MP'), ('U', 'U'), ('p', 'p'), ('peso', 'Peso'), ('Coef', 'Coeficiente')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.indicatorgroup')),
            ],
            options={
                'verbose_name': 'indicador',
                'verbose_name_plural': 'indicadores',
            },
        ),
        migrations.CreateModel(
            name='IndicatorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_records', to='catalog.entity')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='indicators.indicator')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_records', to='catalog.period')),
            ],
            options={
                'verbose_name': 'registro de indicador',
                'verbose_name_plural': 'registros de indicadores',
            },
        ),
        migrations.CreateModel(
            name='IndicatorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='indicators.indicator')),
            ],
            options={
                'verbose_name': 'variable de indicador',
                'verbose_name_plural': 'variables de indicador',
            },
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('indicator', 'name'), name='unique_indicator_code_name'),
        ),
        migrations.AddIndex(
            model_name='indicatorrecord',
            index=models.Index(fields=['entity', 'indicator', 'period'], name='idx_indrec_entity_ind_per'),
        ),
        migrations.AddConstraint(
            model_name='indicatorrecord',
            constraint=models.UniqueConstraint(fields=('entity', 'indicator', 'period', 'variable_name'), name='unique_indicator_record'),
        ),
        migrations.AddConstraint(
            model_name='indicatorvariable',
            constraint=models.UniqueConstraint(fields=('indicator', 'name'), name='unique_indicator_variable'),
        ),
    ]
