# Generated by Django 6.0.3 on 2026-04-22 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
        ('indicators', '0004_seed_indicator_variables'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorrecord',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_records', to='calculations.calculation'),
        ),
        migrations.AddField(
            model_name='indicatorrecord',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_records', to='ingestion.importjob'),
        ),
        migrations.AddField(
            model_name='indicatorrecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('imported', 'Imported'), ('calculated', 'Calculated')], default='manual', max_length=20),
        ),
    ]
