# Generated by Django 6.0.3 on 2026-03-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='catalog.entity')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_classifications', to='catalog.period')),
            ],
            options={
                'verbose_name': 'clasificacion de entidad',
                'verbose_name_plural': 'clasificaciones de entidades',
                'constraints': [models.UniqueConstraint(fields=('entity', 'period', 'classification_type'), name='unique_entity_classification')],
            },
        ),
    ]
