# Generated by Django 6.0.3 on 2026-04-22 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_entity_type_entity_idx_entity_code_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('operational', 'Operacional'), ('executive', 'Ejecutivo')], default='operational', max_length=30)),
                ('status', models.CharField(choices=[('generated', 'Generado'), ('error', 'Error')], default='generated', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
            },
        ),
        migrations.AddIndex(
            model_name='entityclassification',
            index=models.Index(fields=['entity', 'period'], name='idx_class_entity_period'),
        ),
        migrations.AddIndex(
            model_name='entityclassification',
            index=models.Index(fields=['period', 'classification_type'], name='idx_class_period_type'),
        ),
        migrations.AddField(
            model_name='report',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.entity'),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.period'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['entity', 'period'], name='idx_reports_entity_period'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='idx_reports_type_status'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-created_at'], name='idx_reports_created_desc'),
        ),
    ]
