# Generated by Django 6.0.3 on 2026-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_entityclassification_idx_class_entity_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityclassification',
            name='criteria_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entityclassification',
            name='rule_version',
            field=models.CharField(default='r7-v1', max_length=50),
        ),
    ]
